spring:
  data:
    mongodb:
      database: "Aerie"
      uri: "mongodb+srv://aerie696:aerie2022@cluster0.a254omp.mongodb.net"

logging:
  level:
    org:
      mongodb:
        driver: WARN

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
